CREATE TABLE `letters` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`user_id` text NOT NULL,
	`applicant_name` text NOT NULL,
	`relationship` text NOT NULL,
	`duration_known` text NOT NULL,
	`institution` text NOT NULL,
	`target_program` text NOT NULL,
	`target_institution` text NOT NULL,
	`field_domain` text NOT NULL,
	`observed_qualities` text NOT NULL,
	`achievements` text NOT NULL,
	`soft_traits` text NOT NULL,
	`anecdote` text,
	`referrer_name` text NOT NULL,
	`referrer_title` text NOT NULL,
	`referrer_email` text NOT NULL,
	`tone` text NOT NULL,
	`lor_type` text NOT NULL,
	`recommendation_strength` text NOT NULL,
	`content` text,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL,
	FOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE cascade
);
